version: "3"

services:
    web:
        build: .
        command: python manage.py makemigrations --noinput
        command: python manage.py migrate --noinput
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
